{{- if .Values.autoscaling.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gnmic.fullname" . }}-rebalance-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gnmic.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "gnmic.labels" . | nindent 12 }}
          name: {{ include "gnmic.fullname" .}}-rebalance-cronjob
          {{- with .Values.cronjob.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          containers:
          - args:
            - apk add jq curl && curl -s -X POST `curl -s {{ include "gnmic.fullname" . }}-collector-gnmic-api:{{ .Values.service.port }}/api/v1/cluster |  jq .leader | tr -d '"' | awk '{ print $0".{{ include "gnmic.fullname" . }}-collector-gnmic-api" }'`:{{ .Values.service.port }}/api/v1/cluster/rebalance
            image: alpine
            command: ["/bin/sh","-c"]
            imagePullPolicy: IfNotPresent
            name: {{ include "gnmic.fullname" . }}-rebalance
          restartPolicy: Never
  schedule: "{{ .Values.cronjob.schedule  }}"
{{- end }}