{{- if .Values.secrets.secret_provider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    {{- include "gnmic.labels" . | nindent 4 }}
  name:  {{ .Release.Name }}-secretproviderclass
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ .Values.secrets.secret_provider.config.provider }}
  secretObjects:
    - secretName: {{ .Values.secrets.name }}-{{ .Release.Namespace }}
      type: secret
      data:
        {{- range $v := .Values.secrets.secret_provider.objects }}
        - key: {{ $v.env }}
          objectName: {{ $v.name }}
        {{- end }}
  parameters:
    keyvaultName: {{ .Values.secrets.secret_provider.config.keyvault }}
    objects: |
      array:
        {{- range $v := .Values.secrets.secret_provider.objects }}
        - |
          objectName: {{ $v.name }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.secrets.secret_provider.config.tenantId }}
{{- end }}
